codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 1%
        paths:
          - "internal/"
          - "pkg/"
          
    patch:
      default:
        target: 80%
        threshold: 1%
        
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: true
  
ignore:
  - "**/*_test.go"
  - "test/**/*"
  - "examples/**/*"
  - "docs/**/*"
  - "scripts/**/*"
  - "web/templates/**/*"
  - "**/*.templ"
  - "cmd/obtura/main.go" # Main file often has minimal logic